export { ClientHeader } from "./ClientHeader";
export { ExclusiveDeals } from "./ExclusiveDeals";
export { Footer } from "./Footer";
export { HeroBanner } from "./HeroBanner";
export { JoinUs } from "./JoinUs";
export { PopularCategories } from "./PopularCategories";
export { PopularRestaurants } from "./PopularRestaurants";
export { PromoBanner } from "./PromoBanner";
export { Stats } from "./Stats";
